version: "3.9"
services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"

  task_service:
    build: ./task_service
    ports:
      - "8001:8000"
    depends_on:
      - user_service
